version: '3'
services:
  api:
    container_name: cmov-api
    build: .
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=docker
      - DB_NAME=docker
    ports:
      - "8000:8000"
    command: npm start

  postgres:
    container_name: cmov-postgres
    image: postgres:10-alpine
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker

volumes:
  postgres:
